apiVersion: v1
kind: Service
metadata:
    name: "azurecluster-bf69"
    labels:
        app: "azurecluster-bf69"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "azurecluster-bf69"